### PR TITLE
Added a parameter to control async.

### PR DESCRIPTION
**Pull request by groovc**
Added a parameter "as" (for async) that lets you set the script to load synchronously if you want it to otherwise it sets it to true. This is for those edge cases when you do care about script loading order.

### CODE REVIEW

**Comment by zachleat** [comment]
Hey @groovc, what’s the use case for loading JS synchronously?

**Comment by SiamKreative** [comment]
Yeah, what's the point of using an async loader to load stuff synchronously?

**Comment by aFarkas** [comment]
If you set async to false on async created script, it will still load the script async but will execute it in synced order. So basically it adds the behavior.

**Comment by aFarkas** [comment]
Just looking into the PR using the second parameter would be an API change. So can't be merged...

**Comment by scottjehl** [comment]
Closing this out for scope reasons. Thanks, but this lib is only meant for async loading.

**Comment by aFarkas** [comment]
@scottjehl 
I think this should be re-opened. Just changing the API. This is actually the holy grail of async script loading for modern browsers with this technique you can do this:

```js
loadJS('jquery.js', false);
loadJS('jquery-mobile.js', false);
loadJS('jquery-mobile-plugin.js', false);
loadJS('init-mobile-plugin.js', false);
```

As said above all scripts are automatically loaded **async** without blocking, the only difference is that all files are executed in order. If you just think about how much code and workarounds were needed in the past to accomplish this task.

**Comment by scottjehl** [comment]
Thanks @aFarkas - I agree that's nice. reopening to take a further look!

**Comment by aFarkas** [comment]
I think the arguments need to be changed:

Something like this:

```js
function loadJS( src, cb, async ){
	"use strict";
	var ref = window.document.getElementsByTagName( "script" )[ 0 ];
	var script = window.document.createElement( "script" );
	
	if (typeof cb === 'boolean') {
		async = cb;
		cb = null;
	}
	
	script.src = src;
	script.async = async === false ? false : true;
	ref.parentNode.insertBefore( script, ref );
	
	if (cb && typeof(cb) === "function") {
		script.onload = cb;
	}
	
	return script;
}
```

I could put a PR together, if @groovc doesn't fix this issue.

**Comment by vicdango** [comment]
@aFarkas Yes, that was what I was originally thinking...load asynchronously but executed in a specific order. I don't think I was clear in my intention.

**Comment by scottjehl** [comment]
sounds real nice. What’s the browser support for it working as expected, generally?

**Comment by stefanjudis** [comment]
That's nice - but the name `isAsync` might be a bit misleading, or?

**Comment by aFarkas** [comment]
> sounds real nice. What’s the browser support for it working as expected, generally?

http://www.html5rocks.com/en/tutorials/speed/script-loading/?redirect_from_locale=de:
> Loading scripts this way is supported by [everything that supports the async attribute](http://caniuse.com/#search=async), with the exception of Safari 5.0 (5.1 is fine). Additionally, all versions of Firefox and Opera are supported as versions that don’t support the async attribute conveniently execute dynamically-added scripts in the order they’re added to the document anyway.

> That's nice - but the name isAsync might be a bit misleading, or?
As the scripts are all async.

I also thought about this and this would be a change what to pass. Pass `true` instead of `false` and call it `ordered`:

```js
function loadJS( src, cb, ordered ){
    "use strict";
    var ref = window.document.getElementsByTagName( "script" )[ 0 ];
    var script = window.document.createElement( "script" );

    if (typeof cb === 'boolean') {
        ordered = cb;
        cb = null;
    }

    script.src = src;
    script.async = !ordered;
    ref.parentNode.insertBefore( script, ref );

    if (cb && typeof(cb) === "function") {
        script.onload = cb;
    }

    return script;
}
```

My example above would change than to this:

```js
loadJS('jquery.js', true);
loadJS('jquery-mobile.js', true);
loadJS('jquery-mobile-plugin.js', true);
loadJS('init-mobile-plugin.js', true);
```

**Comment by stefanjudis** [comment]
@aFarkas Looks awesome!

**Comment by zachleat** [comment]
@aFarkas doing some old triage and noticed this PR has conflicts. Worth fixing?

**Comment by zachleat** [comment]
Closing in favor of #22

**Pull request closed without merging**
